### ISSUE TITLE
attempt to index global 'defaultConfigFile' (a nil value)

### ISSUE THREAD

**Issue by dragonxtek** [cloudshark/wireshark-plugin#9]
I can't run the plugin. I edit the config file with the API, user and password, also I tried with the original config file without satisfactory results.
This is the issue:
 
```
Lua: Error during loading:
...al/lib/wireshark/plugins/wireshark-plugin/cloudshark.lua:1001: attempt to index global 'defaultConfigFile' (a nil value)
stack traceback:
	...al/lib/wireshark/plugins/wireshark-plugin/cloudshark.lua:1001: in main chunk
```

**Comment by zachad** [comment]
@dragonxtek can you let us know what version of Wireshark you are running?

**Comment by dragonxtek** [comment]
I'm using the Version 3.6.2 (Git v3.6.2 packaged as 3.6.2-2)

**Comment by zachad** [comment]
This error is shown when the default config file `cloudshark.default` is not present on the system. Please reinstall the plugin, or copy [this file from the repo](https://github.com/cloudshark/wireshark-plugin/blob/master/cloudshark.default) into the plugin directory on disk.

After recreating that file, you should restart Wireshark or run "Analyze" -> "Reload Lua Plugins" to pick up the change.

**Comment by dragonxtek** [comment]
I have other plugins working without problems, but only cloudshark gives me a problem.
I have the cloudshark.default and cloudshark.config file in the same folder as the lua file.
I already deleted and installed the file again, but I keep getting the same error. I reloaded wireshark after configuring the plugin and everything is still the same.
What could it be?

**Comment by zachad** [comment]
The error message you're seeing happens when `cloudshark.conf` is missing and needs to be created from the defaults.

What about file permissions? Did you install the plugin to your _personal lua plugins_ or Globally? If the `cloudshark.default` file is not readable by the current user, the same error occurs.

Another workaround is to copy the `cloudshark.default` into `cloudshark.conf` manually, make your changes outside of Wireshark, and then reload.

**Comment by dragonxtek** [comment]
sorry, I needed to rename the folder to cloudshark. Now it works without problems

**Comment by zachad** [comment]
Great catch @dragonxtek. You are correct - it appears this plugin assumes that it is installed in a folder named "cloudshark". Thanks for figuring it out!
